web2project/web2project/apps/web2app/urls.py
from django.urls import path

from . import views

app_name = 'web2app'

urlpatterns = [
	path('', views.login_page, name = 'login_page'),
	path('login', views.login, name = 'login'),
	path('check_login', views.check_login, name = 'check_login'),

	path('note_page/<str:username>', views.note_page, name = 'note_page'),
	path('open_note/<str:username>/<str:theme>', views.open_note, name = 'open_note'),
	path('save_note/<str:username>', views.save_note, name = 'save_note'),
	path('delete_note/<str:username>/<str:theme>', views.delete_note, name = 'delete_note'),
	path('edit_note/<str:username>/<str:theme>', views.edit_note, name = 'edit_note'),

	path('get_users/<str:username>', views.get_users, name = 'get_users'),		
	path('registration_page', views.registration_page, name = 'registration_page'),
	path('registration', views.registration, name = 'registration'),
	path('make_admin/<str:username>', views.make_admin, name = 'make_admin'),
	path('delete_user/<str:username>', views.delete_user, name = 'delete_user'),
	path('main_menu/<str:username>', views.main_menu, name = 'main_menu'),

]

web2project/web2project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('web2app/', include('web2app.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += staticfiles_urlpatterns()

web2project/web2project/apps/web2app/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
	username = models.CharField('Никнейм', max_length=20)
	password = models.CharField('Пароль', max_length=20)
	note_amount = models.IntegerField('Кол-во заметок', default=0)
	last_online = models.DateTimeField('Последний раз в сети', default=timezone.now())
	admin = models.BooleanField('Админка', default=False)

	def __str__(self):
		return self.username

class Note(models.Model):
	theme = models.CharField('Тема заметки', max_length = 30)
	text = models.TextField('Текст заметки', max_length = 404)
	date = models.DateTimeField('Дата создания')
	last_edit = models.DateTimeField('Дата ласт изменения')
	last_user = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.theme

web2project/web2project/apps/web2app/views.py
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from .models import Note, User
from django.urls import reverse
from django.utils import timezone 

from django.urls import reverse

def login_page(request):
	return render(request, 'web2app/login_template.html')

def check_login(request):
	user = User.objects.filter(username = request.POST['username'], password = request.POST['password'])
	if(len(user) != 0):
		response = {'bool': True}
		return render(request, 'web2app/form.html', {'user': user[0]})		
	else:
		response = {'bool': False}
		return JsonResponse(response)

def login(request):
	user = User.objects.filter(username = request.POST['username'], password = request.POST['password'])
	if(len(user) != 0):
		user_temp = user[0]
		user_notes = user_temp.note_set.all()
		return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': user_temp})			
		

def registration_page(request):
	return render(request, 'web2app/registration_template.html', {'bool': -1})


def registration(request):
	username = request.POST['Username1']
	password = request.POST['Password1']
	confirm_password = request.POST['Confirm_password1']
	mod = request.POST['mod']
	if (mod == 'Admin'):
		admin = True
	else:
		admin = False

	if (password == confirm_password):
		user = User(username=username, password=password, admin = admin)
		user.save()
		user_notes = []
		return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': user})
	else:
		return render(request, 'web2app/registration_template.html', {'bool': 0})

def note_page(request, username):
	return render(request, 'web2app/note_template.html', {'username': username, 'bool_create': 1})

def save_note(request, username):
	theme = request.POST['theme']
	text = request.POST['text']
	date = timezone.now()
	last_edit = date
	last_user = User.objects.get(username=username)
	note = Note(theme=theme, text=text, date=date, last_edit=last_edit, last_user=last_user)
	note.save()
	user_notes=last_user.note_set.all()
	last_user.note_amount = len(user_notes)
	last_user.save()	
	return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': last_user})

def open_note(request, username, theme):
	user = User.objects.get(username = username)
	note = user.note_set.all().get(theme=theme)
	return render(request, 'web2app/note_template.html', {'note': note,'username': username, 'bool_create': 0})

def delete_note(request, username, theme):
	user = User.objects.get(username = username)
	note = user.note_set.all().get(theme=theme)
	user.save()
	note.delete()
	user_notes=user.note_set.all()
	user.note_amount = len(user_notes)
	user.save()
	return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': user})

def edit_note(request, username, theme):
	user = User.objects.get(username = username)
	note = user.note_set.all().get(theme=theme)
	note.theme = request.POST['theme']
	note.text = request.POST['text']
	note.save()
	user_notes=user.note_set.all()
	return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': user})

def get_users(request, username):
	users = User.objects.all()
	user = User.objects.get(username = username)
	return render(request, 'web2app/users_template.html', {'users': users, 'user_x': user} )

def make_admin(request, username):
	user = User.objects.get(username = username)
	user.admin = True;
	user.save()
	return HttpResponseRedirect( reverse('web2app:get_users', args = (username,)))

def delete_user(request, username):
	user = User.objects.get(username = username)
	user.delete()
	return HttpResponseRedirect( reverse('web2app:get_users', args = (username,)))

def main_menu(request, username):
	user = User.objects.get(username = username)
	user_notes=user.note_set.all()
	return render(request, 'web2app/main_page.html', {'user_notes': user_notes, 'user': user})

web2project/web2project/templates/LogInPage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-image {
  /* The image used */
  background-image: url("{% static "images/img_parallax.jpg" %}");
  
  /* Add the blur effect */
  filter: blur(8px);
  -webkit-filter: blur(8px);
  
  /* Full height */
  height: 100%; 
  
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* Position text in the middle of the page/image */
.bg-text {
  	display: flex;
  	flex-direction: column;
  	border-radius: 15px;
	background-color: rgb(0,0,0); /* Fallback color */
	background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
	color: white;
	font-weight: bold;
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	z-index: 1;
	width: 50%;
	height: 70%;
	padding: 20px;
	text-align: center;
}
a {
  color: white;
  font-size: 16px;;
}

.login-error {
  color: red;
  font-size: 16px;
}
</style>
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}"/>
</head>
<body>

<div class="bg-image"></div>

<div class="bg-text">
    <p style="font-size:50px"> Member login </p>

    {% block login_action %}
    {% endblock %}

    <div class="acc"><a href="registration_page"> Create your account</a></div>
</div>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ajax_login.js' %}"></script>
</html>

web2project/web2project/templates/RegistrationPage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-image {
  /* The image used */
  background-image: url("{% static "images/img_parallax.jpg" %}");
  
  /* Add the blur effect */
  filter: blur(8px);
  -webkit-filter: blur(8px);
  
  /* Full height */
  height: 100%; 
  
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* Position text in the middle of the page/image */
.bg-text {
  	display: flex;
  	flex-direction: column;
    border-radius: 15px;
  	background-color: rgb(0,0,0); /* Fallback color */
  	background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
  	color: white;
  	font-weight: bold;
  	position: absolute;
  	top: 50%;
  	left: 50%;
  	transform: translate(-50%, -50%);
  	z-index: 1;
  	width: 50%;
  	height: 70%;
  	padding: 20px;
  	text-align: center;
}

.reg-error {
  color: red;
  font-size: 16px;
}

.admin-cont {
  display: flex;
  flex-direction: column;
}


</style>
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}"/>
</head>
<body>

<div class="bg-image"></div>

<div class="bg-text">
    <p style="font-size:50px"> Sign up </p>
    {% block registration_action %}
    {% endblock %}
</div>

</body>
</html>

web2project/web2project/templates/WatchUsers.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

body {
        background-image: url("{% static "images/img_parallax.jpg" %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: 100%;
        max-height: 100%;
        margin: 0;
        font-size: 100%
        -moz-background-size: 100%; /* Firefox 3.6+ */
        -webkit-background-size: 100%; /* Safari 3.1+ и Chrome 4.0+ */
        -o-background-size: 100%; /* Opera 9.6+ */
    }

/* Position text in the middle of the page/image */
.bg-text {
  	display: flex;
  	flex-direction: column;
  	border-radius: 15px;
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
    color: white;
    font-weight: bold;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 1;
    width: 50%;
    height: 70%;
    padding: 20px;
    text-align: center;
}
a {
  color: white;
}

.button-note {
        background-color: rgba(1, 1, 1, 0);
        border-radius: 20px;
        height: 12em;
        max-height: 11em;
        min-width: 15em;
        width: 100%;
        margin-bottom: 5%;
        margin-right: 3%;
    }
  .username {
    font-family: sans-serif;
    font-size: 16px;
    color: black;
    align-self: center;
  }

  .back-button-cont{
    display: flex;
    flex-direction: row;
    justify-content: center;
  }

  .users-cont{
    display: flex;
    flex-direction: row;
    justify-content: center;
    width: 100%;
    margin-bottom: 10px;
  }

  .user-text{
    font-family: sans-serif;
    font-size: 45px;
    color: white;
  }


</style>
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/item.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/containers.css' %}"/>

</head>
<body>

    {% block users%} {% endblock%}


</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ajax_users.js' %}"></script>
</html>

web2project/web2project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        background-image: url("{% static "images/img_parallax1.jpg" %}");
        /* Full height */
  height: 100%; 
  
  /* Center and scale the image nicely */
  background-size: cover;
    }

    .down-container {
        display: flex;
        flex-direction: row;
        justify-content: start;
        flex-wrap: wrap;
        margin-right: 20%;
        margin-left: 20%;
        margin-bottom: 5px;
    }


    @media only screen and (max-width: 950px) {

        .down-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-right: 3%;
            margin-left: 4%;
            margin-bottom: 0;
            justify-content: center;
        }

        
    }

    p.user {
        font-size: 1.4em;
        font-family: sans-serif;
        margin-right: 1.5%;
    }

    .NoNotes{
        color: white;
        font-size: 30px;
        font-family: sans-serif;
        text-align: center;
    }

    .text-bucket{
        display: flex;
        flex-direction: row;
        justify-content: center;
        width: 100%;
    }

    h2 {
        overflow: hidden;
        color: rgb(87, 87, 87);
        font-size: 15px;
    }
 
    .button-note {
        background-color: rgba(1, 1, 1, 0);
        border-radius: 20px;
        height: 12em;
        max-height: 11em;
        min-width: 15em;
        width: 100%;
        margin-bottom: 5%;
        margin-right: 3%;
    }

    
    </style>
    <link rel="stylesheet" href="{% static 'css/containers.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/item.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}"/>
</head>

<body>
    <div class="container">
        <div class="upper-container">
            <p id="MyNOTES"> MyNOTES </p>
        </div>
        <div class="down-container">
            <div class="button butt5"> {% block user_name %} {% endblock %} </div>
            {% block all_buttons %} {% endblock %}
            <!--
            <div class="sort-button" onClick='location.href="WatchUsers.htm"'> Users </div>
            <div class="sort-button" onClick='location.href="WatchUsers.htm"'> LogOut </div>
            <div class="topnav sub">
                <input type="text" placeholder="Search note...">
            </div> -->
        </div>
                 
           {% block notes %} {% endblock %}
        
    </div>
</body>

</html>

web2project/web2project/templates/note.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/335f954d3a.js" crossorigin="anonymous"></script>
    <style>
        body,
        html {
            height: 100%;
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }
        
        * {
            box-sizing: border-box;
        }
        
        .bg-image {
            /* The image used */
            background-image: url("{% static "images/img_parallax.jpg" %}");
            /* Add the blur effect */
            filter: blur(8px);
            -webkit-filter: blur(8px);
            /* Full height */
            height: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        /* Position text in the middle of the page/image */
        
        .bg-text {
            display: flex;
            flex-direction: column;
            border-radius: 15px;
            align-items: center;
            background-color: rgb(0, 0, 0);
            /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4);
            /* Black w/opacity/see-through */
            color: white;
            font-weight: bold;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 1;
            width: 50%;
            height: 50%;
            padding-bottom: 50px;
            text-align: center;
        }
        
        a {
            color: white;
        }
        
        p.theme {
            font-family: sans-serif;
            font-size: 16px;
        }
        
        textarea {
            border-radius: 15px;
            height: 40%;
            width: 60%;
            font-size: 1.5em;
        }

    .Delete {
        color: #5e5e5e;
        user-select: none;
        background-color: #ededed;
        border: none;
        border-radius: 10px;
        width: 10%;
        height: 100%;
        padding-top: 3px;
        margin-top: 5px;
        box-shadow: 0 0 0.2em #010b23;
    }

    .save-delete{
        display: flex;
        flex-direction: row;
        width: 60%;
        height: 40px;
        justify-content: space-between;
    }
        
    .save-button {
        background-color: #18c420;
        border: none;
        width: 40%;
        height: 50px;
        border-radius: 10px;
        font-size: 16px;
        font-family: sans-serif;
        margin-top: 5px;
        box-shadow: 0 0 0.2em #010b23;
    }

    .text {
        height: 50%;
    }

    </style>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}" />


</head>

<body>
    <div class="bg-image"></div>
    {% block content %}{% endblock %}
</body>

</html>

web2project/web2project/templates/web2app/form.html
<form action="{% url 'web2app:login' %}" method="POST">
	{% csrf_token %}
	<div class="topnav">
		<input  type="text" placeholder="Login" required name="username" value="{{user.username}}">    
	</div> 
	<div>
		<input type="password" placeholder="Password" required name="password" value="{{user.password}}" >    
	</div>
	<input class="login_button" type="submit" ></input>
</form>
		

web2project/web2project/templates/web2app/index.htm
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    * {
        box-sizing: border-box;
    }



    body {
        {% load static %}
        background-image: url("{% static "web2app/img_parallax.jpg" %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: 100%;
        max-height: 100%;
        margin: 0;
        font-size: 100%
        -moz-background-size: 100%; /* Firefox 3.6+ */
        -webkit-background-size: 100%; /* Safari 3.1+ и Chrome 4.0+ */
        -o-background-size: 100%; /* Opera 9.6+ */
    }

    .down-container {
        display: flex;
        flex-direction: row;
        justify-content: center;
        flex-wrap: wrap;
        margin-right: 3%;
        margin-left: 4%;
        margin-bottom: 0;
    }


    @media only screen and (max-width: 950px) {

        .down-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-right: 3%;
            margin-left: 4%;
            margin-bottom: 0;
            justify-content: center;
        }

        
    }

    p.user {
        font-size: 1.4em;
        font-family: sans-serif;
        margin-right: 1.5%;
    }
    </style>
    <link rel="stylesheet" href="{% static 'css/containers.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/item.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/search_field.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}"/>
</head>

<body>
    <div class="container">
        <div class="upper-container">
            <p id="MyNOTES"> MyNOTES </p>
        </div>
        <div class="down-container">
            <p class="button butt5"> Use_name </p>
            <div class="button butt1"> New note </div>
            <div class="button butt3"> Select note </div>
            <div class="button butt4"> Delete note </div>
            <div class="button butt2" onClick='location.href="WatchUsers.htm"'> Users </div>
            <div class="button butt1" onClick='location.href="LogInPage.htm"'> Log out </div>
            <div class="topnav sub">
                <input type="text" placeholder="Search note...">
            </div>
        </div>
        <div class="main">
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
            <div class="item" onClick='location.href="note.htm"'>
                <h1>THEME</h1>
                <h2>some text...</h2>
            </div>
        </div>
    </div>
</body>

</html>

web2project/web2project/templates/web2app/login_template.html
{% extends 'LogInPage.html' %}

{% block login_action %}

	<div id="dynamic">
		<form id="login-form">

		{% csrf_token %}
		<div class="topnav">
			<input  type="text" placeholder="Login" required id="username" >    
		</div> 
		<div>
			<input type="password" placeholder="Password" required id="password" >    
		</div>
		<div class="login-error" id="login_error"></div>
		<input class="login_button" type="submit" value="Login"></input>
		</form>
	</div>

{% endblock %}

web2project/web2project/templates/web2app/main_page.html
{% extends 'base.html' %}

{% block notes %}
<div class="main">
	{% if user_notes%}
		{% for element in user_notes%}			
				<form action="{% url 'web2app:open_note' user.username element.theme %}" class="button-note">
					<button class="item">
						<h1>{{element.theme}}</h1>
						<h2>{{element.text}}</h2>						
					</button>
				</form>
		{% endfor %}
	{% else %}
		<div class="text-bucket"> <div class="NoNotes">Oops, it seems like you haven`t add any notes yet, </br> try now CLICK NEW NOTE </div></div>
	{% endif %}
</div>
{% endblock %}

{% block user_name%}
	{{user.username}}
{% endblock%}

{% block all_buttons%}
	<form action="{% url 'web2app:note_page' user.username %}" >
		{% csrf_token %}
		<button class="sort-button" style="width: 160px"> New note </button>
	</form>
	{% if user.admin %}
		<form action="{% url 'web2app:get_users' user.username%}" >
			{% csrf_token %}
			<button class="sort-button" style="width: 160px"> Users </button>
		</form>
	{% endif %}
	<form action="{% url 'web2app:login_page' %}" >
		{% csrf_token %}
		<button class="sort-button" style="width: 160px"> Log out </button>
	</form>
{% endblock%}

web2project/web2project/templates/web2app/note_template.html
{% extends "note.html" %}

{% block content %}

{% if bool_create %}
    <form action="{% url 'web2app:save_note' username %}" method="POST">
        {% csrf_token %}
            <div class="bg-text">
                <p style="font-size:50px"> Theme </p>               
                <textarea name="theme" placeholder="Тема" style="height:50px"></textarea>
                <textarea name="text" placeholder="Оставьте ваш текст " class="text"></textarea>                  
                <button type="submit" class="save-button">Save</button>
            </div>
    </form>
{% else %}
    <form action="{% url 'web2app:edit_note' username note.theme %}" method="POST">
        {% csrf_token %}
            <div class="bg-text">
                <p style="font-size:50px"> Theme </p>
                <textarea name="theme" placeholder="Тема" style="height:50px">{{note.theme}}</textarea>
                <textarea name="text" placeholder="Оставьте ваш текст " class="text">{{note.text}}</textarea>
                <div class="save-delete">
                    <button type="submit" class="save-button">Save</button>
                    <div class="Delete" onClick='location.href="{% url 'web2app:delete_note' username note.theme %}"'><i class="far fa-trash-alt fa-2x"></i></div>
                </div>
            </div>
    </form>
{% endif%}


{% endblock %}

web2project/web2project/templates/web2app/registration_template.html
{% extends 'RegistrationPage.html' %}

{% block registration_action %}

	<form action="registration" method="POST">
		{% csrf_token %}
		<div class="topnav">
			<input  type="text" placeholder="Username" required name = "Username1">    
		</div> 
		<div class="topnav">
			<input  type="text" placeholder="Password" required name = "Password1">    
		</div>
		<div class="topnav">
			<input  type="text" placeholder="Confirm password" required name = "Confirm_password1">    
		</div>
		{% if bool == 0 %}
			<div class="reg-error"> Passwords don't match </div>
		{% endif %}
		<div class="admin-cont">
			<select name="mod" class="new-select-style-wpandyou">
				<option value="Admin">Admin</option>
				<option value="Regular">Regular</option>
			</select>
			<input type="submit" class="login_button" value="Create an account">
		</div>
    </form>

{% endblock %}

web2project/web2project/templates/web2app/users_template.html
{% extends 'WatchUsers.html' %}

{% block users %}

<div class="main" style="margin-top: 10%">
    <div class="users-cont"> <div class="user-text">Users </div> </div>

	{% if users %}
	
		{% for user in users%}
		
		<div class="user-cont" id ="user-cont/{{user.username}}" >			
			<div class="username" id="make_admin/{{user.username}}/text"> {{user.username}}{% if user.admin%} - admin {% endif%} </div>
			<div class="username"> {{user.note_amount}} {% if user.note_amount == 1%} note {% else %} notes {% endif%} </div>			
			{% if user.username != user_x.username%}
				<div id = "make_admin/{{user.username}}" class="make-admin-cont">
					<button class="make-admin" type="submit" onClick='make_admin(this.parentElement.id)'>make admin</button>						
				</div>
				<div id = "delete_user/{{user.username}}" class="make-admin-cont">
					<button class="delete-user" type="submit" onClick='delete_user(this.parentElement.id)'>delete</button>		
				</div>
			{% endif%}
		</div>
		
					
		{% endfor %}
		
	{% else %}
		<div class="NoNotes"> Oops, it seems like something went wrong </div>
	{% endif %}

</div>
<div class="back-button-cont">
	<button class="login_button back" type="submit" onClick='location.href="{% url 'web2app:main_menu' user_x.username %}"'>back</button>		
</div>

{% endblock %}